 services:
  agency:
    image: acapy-test
    ports:
      - "3001:3001"
    environment:
      RUST_LOG: 'aries-askar::log::target=error'
    command: >
      start
        --label Agency
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://agency:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --no-ledger
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --debug-webhooks
        --multitenant
        --multitenant-admin
        --jwt-secret insecure
        --multitenancy-config wallet_type=single-wallet-askar key_derivation_method=RAW
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - AGENCY=http://agency:3001
    volumes:
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      agency:
        condition: service_healthy
